(import (rnrs))

(define (triangle a b c)
  (cond
   ((or (<= a 0)
        (<= b 0)
        (<= c 0)
        (<= (+ a b) c)
        (<= (+ a c) b))
    (error 'triangle "invalid triangle"))
   ((= a b c)
    'equilateral)
   ((or (= a b)
        (= b c)
        (= a c))
    'isosceles)
   (else 'scalene)))
